<?php
$this->headTitle("Đổi mật khẩu");
$form->prepare();
?>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h2><?=$this->escapeHtml("Đổi mật khẩu")?></h2>
    <div><?=$this->flashMessenger()->render('error',['alert','alert-danger'])?></div>
        <?=$this->form()->openTag($form)?>
        
        <div class="form-group">
        <?=$this->formLabel($form->get('old_pw'));?>
            <div class="col-md-6">
                <?php
                echo $this->formElement($form->get('old_pw'));
                echo $this->formElementErrors($form->get('old_pw'));
                ?>
            </div>
        </div>
        <div class="form-group">
        <?=$this->formLabel($form->get('new_pw'));?>
            <div class="col-md-6">
                <?php
                echo $this->formElement($form->get('new_pw'));
                echo $this->formElementErrors($form->get('new_pw'));
                ?>
            </div>
        </div>
        <div class="form-group">
        <?=$this->formLabel($form->get('confirm_new_pw'));?>
            <div class="col-md-6">
                <?php
                echo $this->formElement($form->get('confirm_new_pw'));
                echo $this->formElementErrors($form->get('confirm_new_pw'));
                ?>
            </div>
        </div>
        <?php echo $this->formElement($form->get('csrf'));?>
        <div class="form-group">
            <div class="col-md-2 col-md-offset-10">
                <?=$this->formElement($form->get('submit'));?>
            </div>
        </div>
        <?=$this->form()->closeTag()?>
    </div>
</div>
