<?php
$title = "Danh sách User";
$this->headTitle($title);
?>
<h2><?=$title?></h2>
<div class="col-md-4 col-md-offset-4"><?=$this->flashMessenger()->render('success',['alert', 'alert-success'])?></div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>STT</th>
            <th>Username</th>
            <th>Email</th>
            <th>Fullname</th>
            <th>Birthday </th>
            <th>Phone</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php $stt = 1;
        foreach($users as $user):?>
        <tr>
            <td><?=$stt?></td>
            <td><?=$this->escapeHtml($user->getUsername())?></td>
            <td><?=$this->escapeHtml($user->getEmail())?></td>
            <td><?=$this->escapeHtml($user->getFullname())?></td>
            <td><?=$user->getBirthdate()->format('d-m-Y')?></td>
            <td><?=$this->escapeHtml($user->getPhone())?></td>
            <td>
                <a href="<?=$this->url('user',['action'=>'edit','id'=>$this->escapeHtml($user->getId())])?>">Edit</a> | Delete</td>
        </tr>
        <?php 
        $stt++;
        endforeach?>
    </tbody>
</table>
