<?php
$this->headTitle("Quên mật khẩu");
$form->prepare();
?>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h2><?=$this->escapeHtml("Quên mật khẩu")?></h2>
    <div><?=$this->flashMessenger()->render('error',['alert','alert-danger'])?>
    <?=$this->flashMessenger()->render('success',['alert','alert-success'])?></div>
        <?=$this->form()->openTag($form)?>
        
        
        <div class="form-group">
        <?=$this->formLabel($form->get('email'));?>
            <div class="col-md-6">
                <?php
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><?=$this->formLabel($form->get('captcha_image'));?></div>
            <div class="col-md-12">
                <?php
                echo $this->formElement($form->get('captcha_image'));
                echo $this->formElementErrors($form->get('captcha_image'));
                ?>
            </div>
        </div>
        <?php echo $this->formElement($form->get('csrf'));?>
        <div class="form-group">
            <div class="col-md-2 col-md-offset-10">
                <?=$this->formElement($form->get('submit'));?>
            </div>
        </div>
        <?=$this->form()->closeTag()?>
    </div>
</div>
