<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Started</title>
</head>
<body>
    <h1>Hello World!</h1>
    <h3>Hello Khoa Phạm</h3>
    <br>
    <a href="started/login">Go to Login Page</a>
    <a href="started/register">Go to Register Page</a>
</body>
</html>