<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?=$this->HeadTitle('Login Page')?></title>
</head>
<body>
    <h2>This  is Login Page 2</h2>
    <div>
    <?=$this->escapeHtml($name);?>
    <br>
    <?=$this->escapeHtml($id);?>
    <br>
    <?=$this->escapeHtml($method);?>
    <br>
    <?=$method?>
    </div>
</body>
</html>