<?php

$contactForm = $this->form;
$fullname = $contactForm->get('fullname');
$pw = $contactForm->get('my_password');
$hidden = $contactForm->get('hidden_input');
$color = $contactForm->get('my_color');
$date = $contactForm->get('date');
$range = $contactForm->get('my_range');
$csrf = $contactForm->get('token');
$submit = $contactForm->get('btnSubmit');

?>

<div class="row">    
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
        <?php
        echo $this->form()->openTag($contactForm);
        echo $this->FormRow($fullname);
        echo '<br>';
        echo $this->FormRow($pw);
        echo '<br/>';
        echo $this->FormRow($hidden);
        echo $this->FormRow($color);
        echo '<br/>';
        echo $this->FormRow($date);
        echo '<br/>';
        echo $this->FormRow($range);
        echo '<br/>';
        echo $this->FormRow($csrf);
        echo $this->FormRow($submit);
        echo $this->form()->closeTag($contactForm);
        
        ?> 
    </div>    
</div>