<?php
$title = 'User Login';
$this->headTitle($title);

$form = $this->form;
$form->setName('login');
$form->setAttributes([
    'class'=>'form-horizontal',
    'id'=>'login-form',
    'action'=>'#'
]);

$form->prepare();
echo $this->form()->openTag($form); //<form>
?>

<div class="row">
    
    <div class="col-md-4 col-md-offset-4">
        <h2><?=$this->escapeHtml($title)?></h2>
        <?=$this->flashMessenger()->render('error',['alert','alert-danger'])?>
    <div class="form-group">
    <?=$this->formLabel($form->get('username'));?>
        <div class="col-md-9">
            <?php
            echo $this->formElement($form->get('username'));
            echo $this->formElementErrors($form->get('username'));
            ?>
        </div>
    </div>
    <div class="form-group">
        <?=$this->formLabel($form->get('password'));
        ?>
        <div class="col-md-9">
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
        ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
        <?php
        
            echo $this->formElement($form->get('remember'));
            echo $this->formLabel($form->get('remember'));
        ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
           <a href="<?=$this->url('resetpassword')?>">Forget Password?</a>
        </div>
        <div class="col-md-3">
            <?php
                echo $this->formRow($form->get('submit'));
            ?>
        </div>
    </div>
    <?php
    echo $this->form()->closeTag(); //</form>
    ?>
    </div>
</div>
