<?php
$title = 'Xóa món ăn';

$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1><?= $this->escapeHtml($title) ?></h1>

        <div>Bạn có chắc chắn mốn xóa
            "<?= $this->escapeHtml($foods->name) ?>" không?
        </div>
        <div><img src="../../img/hinh_mon_an/<?=$foods->image?>" width="150px"></div>
        <hr>
        <form action="<?=$this->url('foods', ['action' => 'delete', 'id' => $id])?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $id ?>" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        </div>
        </form>
        
    </div>
</div>
