<?php
$title = 'Upload Multiple File';
$this->headTitle($title);

$form = $this->form;
$form->setAttributes([
    'enctype'=>'multipart/form-data',
    'action' => $this->url('file',[
        'controller'=>'Controller\UploadfileController',
        'action'=>'uploadMultiple'
    ]),
    'method'=>'POST'
]);

$form->prepare();
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2><?=$this->escapeHtml($title)?></h2>
    <?php

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('file-upload'));
        echo $this->formRow($form->get('btnSubmit'));
        echo $this->form()->closeTag();
    ?>
    </div>
</div>
